[maia.exe]
lc0_path = "../assets/maia/lc0.exe"

[maia.weights]
maia_1100 = "../assets/maia/maia-1100.pb.gz"
maia_1400 = "../assets/maia/maia-1400.pb.gz"
maia_1600 = "../assets/maia/maia-1600.pb.gz"
maia_1900 = "../assets/maia/maia-1900.pb.gz"

[positions]
path = "positions.epd"